sudo: require
services:
  - docker

before_install:
    - docker build -t bleibig/docker-react -f Dockerfile.dev .

script:
  - docker run bleibig/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-431215843632"
  bucket_paht: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
